<?php
namespace FamilyTree365\OpenArch;

use Illuminate\Support\ServiceProvider;

class OpenArchServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->mergeConfigFrom(__DIR__.'/config/open-arch.php', 'open-arch');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        if ($this->app->runningInConsole()) {

            $this->publishes([
                __DIR__.'/config/open-arch.php' => config_path('open-arch.php'),
            ], 'config');

        }
    }
}
